### PR TITLE
Just adding morning greeting & exception of startRTM 

### PR DESCRIPTION
**Pull request by tatsushitoji**
## I did
- [x] add exception of failed to connect Slack
- [x] add morning greeting 
- [x] add above implementation to existing code

## I'd like to do later
-  this implemantation's unit testing

## merge condition
- [x] all ✅ CI status
- [x] approve of @1natsu172
- [x] approve of @bom-shibuya

### CODE REVIEW

**Review by 1natsu172 — APPROVED** [review]
🆗 👍 🆗 👍 ⭕️ 🙆‍♂️

**Comment by bom-shibuya** [comment]
🆗🙇🙇🙇👍👍

**Comment by tatsushitoji** [comment]
thx guys!
I will merge this PR later 🙏

**Review by bom-shibuya — APPROVED** [review]
🙏👍👍👍

**Pull request merged**
